[workspace]
[package]
version = "0.1.0"
name = "beacons"
edition = "2021"

[dependencies]
serde_json = "1.0.117"
sp1-zkvm = { git = "https://github.com/succinctlabs/sp1.git", rev = "v1.0.0-testnet"  }
